### PR TITLE
comaptibily with newer python collections.abc issue

### PR DESCRIPTION
**Pull request by radkujawa**
I'm using terraformpy and this is really great tool

Currently I use python 3.7, but wanted to switch to python 3.10

however, terraformpy is not compatible yet

This fix makes terraformpy compatible with python > 3.8 and preserves backward compatibility with older python versions.

### CODE REVIEW

**Comment by radkujawa** [comment]
@harlokaur @luislew @borgstrom ?
I think I fixed Travis CI but I cannot execute it again, could somebody help me with this PR?

**Comment by luislew** [comment]
@radkujawa Right now, the Travis CI builds are blocked because we're out of credits ☹️ I updated our `.travis.yml` file to use the free architecture but it didn't work, possibly because we already have a negative balance. 

From https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution:
> In order to start a build in the Usage-based Plan, a positive credits balance is required in the account (at least 1 credit). The build job under Partner Queue Solution costs 0 credits per started minute. At the moment of introducing Partner Queue Solution, active accounts on the Usage-based Plans, including the Free Plan, with a balance of zero or fewer credits, are updated to hold 1 credit. Thus everybody can use Partner Queues without requesting Travis CI support to grant additional credits. If you run into a negative account balance after that, you still need to file an additional request.

So, we may need to file a request to Travis CI to get this fixed.

**Comment by luislew** [comment]
I just opened a support ticket with Travis CI - 🤞🏻 they can unblock our builds.

**Comment by radkujawa** [comment]
thank you very much! :)

**Review by luislew — APPROVED** [review]

**Comment by luislew** [comment]
@radkujawa we got credits, and there's now a new version of `terraformpy` available - https://pypi.org/project/terraformpy/1.3.4/

**Pull request merged**
